apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-emoji-svc
  labels:
    app: {{ .Release.Name }}-emoji-svc
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.api.emoji.maxunavilable }}
      maxSurge: {{ .Values.api.emoji.maxsurge }}
  replicas: {{ .Values.api.emoji.replicas }}
  revisionHistoryLimit: {{ .Values.api.emoji.revisionLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-emoji-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-emoji-svc
    spec:
      containers:
      - name: {{ .Release.Name }}-emoji-svc
        image: {{ .Values.api.emoji.image.name }}:{{ .Values.api.emoji.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.api.emoji.port }}
          name: gprc
        env:
          - name: GRPC_PORT
            value: {{ .Values.api.emoji.port | quote }}
        resources:
          requests:
            memory: {{ .Values.api.emoji.requests.memory | quote }}
            cpu: {{ .Values.api.emoji.requests.cpu | quote }}
          limits:
            memory: {{ .Values.api.emoji.limits.memory | quote }}
            cpu: {{ .Values.api.emoji.limits.cpu | quote }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.api.emoji.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: {{ .Values.api.emoji.port }}
          initialDelaySeconds: 5
          periodSeconds: 10 


            
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emoji-svc
spec:
  selector:
    app: {{ .Release.Name }}-emoji-svc
  ports:
  - name: grpc
    port: 8081
    targetPort: {{ .Values.api.emoji.port }}
