apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    type: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.api.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-web
          servicePort: 80
